### ISSUE TITLE
Question about the albedo

### ISSUE THREAD

**Issue by shuangw98** [ziyc/L-Tracing#1]
Hi, thank your for this work! 
In the repository, when calculating the PSNR of albedo, you apply gamma correction only to the predicted albedo but not the ground truth. Did I misunderstand anything?

**Comment by ziyc** [comment]
Gamma correction is applied to the predicted albedo to align its brightness with human perception, ensuring that the model output appears visually consistent. This adjustment is not extended to the ground truth albedo since it is already within a reasonable brightness range. The goal is to maintain a fair and accurate comparison between the model predictions and ground truth, considering their inherent luminance characteristics.
